version: '3.5'
services: 
  subtitles-app:
    container_name: subtitles-app
    build: 
      context: ./subtitles-app
      dockerfile: Dockerfile
    volumes:
      - './subtitles-app:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    environment: 
      - NODE_ENV=development
  subtitles-web:
    container_name: subtitles-server
    build:
      context: ./subtitles-server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'